#!/bin/zsh
failed=0
for i in test/*; do
    [[ ! -d $i ]] && continue
    echo "=========="
    echo "Running ${i:t} tests"
    echo "----------"
    for j in $i/test*; do
        [[ ! -x $j ]] && continue
        $j
        [[ $? -ne 0 ]] && failed=1
        echo
    done
done
exit $failed
